apiVersion: v1 
kind: Pod 
metadata: 
  name: web-app 
  namespace: test-ns 
spec: 
  containers:
    - name: sample-web 
      image: muralisocial123/devops-web:2.0
      ports:
        - containerPort: 80